#!/usr/bin/env sh
set -eu

APP_DIR="${APP_DIR:-$(pwd)}"
ENV_FILE="${APP_DIR}/.env"

read_input() {
  prompt="$1"
  default="${2:-}"

  if [ -n "$default" ]; then
    printf "%s [%s]\n> " "$prompt" "$default" >&2
  else
    printf "%s\n> " "$prompt" >&2
  fi

  read -r value || true

  if [ -z "$value" ]; then
    value="$default"
  fi

  printf "%s" "$value"
}

read_required() {
  prompt="$1"
  default="${2:-}"

  while true; do
    value=$(read_input "$prompt" "$default")

    if [ -n "$value" ]; then
      printf "%s" "$value"
      return 0
    fi

    printf "此项不能为空，请重新输入。\n\n" >&2
  done
}

yes_no() {
  prompt="$1"
  default="${2:-n}"

  if [ "$default" = "y" ]; then
    suffix="[Y/n]"
  else
    suffix="[y/N]"
  fi

  printf "%s %s\n> " "$prompt" "$suffix" >&2
  read -r value || true

  if [ -z "$value" ]; then
    value="$default"
  fi

  value=$(printf "%s" "$value" | tr '[:upper:]' '[:lower:]')

  case "$value" in
    y|yes) return 0 ;;
    *) return 1 ;;
  esac
}

printf "\n"
printf "qBittorrent Telegram Bot 配置向导\n"
printf "=================================\n\n"
printf "说明：为了兼容 Unraid 终端，本向导采用可见输入。\n"
printf "请不要在公开屏幕或录屏环境下输入 Token 和密码。\n\n"

TELEGRAM_TOKEN=$(read_required "请输入 Telegram Bot Token")
ADMIN_CHAT_IDS=$(read_input "请输入允许控制 Bot 的 Telegram Chat ID，可先留空" "")

printf "\n"

if yes_no "是否使用本地 Telegram Bot API" "n"; then
  USE_LOCAL_TELEGRAM_API="true"
  TELEGRAM_API_BASE=$(read_required "请输入本地 Telegram Bot API 地址" "http://127.0.0.1:8081")
  LOCAL_TELEGRAM_FILE_ROOT=$(read_input "请输入容器内本地 Telegram 文件根目录" "/var/lib/telegram-bot-api")
else
  USE_LOCAL_TELEGRAM_API="false"
  TELEGRAM_API_BASE="https://api.telegram.org"
  LOCAL_TELEGRAM_FILE_ROOT="/var/lib/telegram-bot-api"
fi

printf "\n"

QBT_SCHEME=$(read_input "请输入 qBittorrent 协议：http 或 https" "http")
QBT_HOST=$(read_required "请输入 qBittorrent IP 或域名" "127.0.0.1")
QBT_PORT=$(read_required "请输入 qBittorrent WebUI 端口" "8080")
QBT_URL="${QBT_SCHEME}://${QBT_HOST}:${QBT_PORT}"

QBT_USERNAME=$(read_required "请输入 qBittorrent 用户名" "admin")
QBT_PASSWORD=$(read_required "请输入 qBittorrent 密码")
QBT_SAVE_PATH=$(read_input "请输入 qBittorrent 下载路径，可留空使用默认路径" "")
QBT_CATEGORY=$(read_input "请输入 qBittorrent 分类" "telegram")
QBT_TAGS=$(read_input "请输入 qBittorrent 标签" "telegram")

printf "\n"

if yes_no "添加任务后是否先暂停/停止" "n"; then
  ADD_STOPPED="true"
else
  ADD_STOPPED="false"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/configure.sh

TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
TELEGRAM_API_BASE=${TELEGRAM_API_BASE}
ADMIN_CHAT_IDS=${ADMIN_CHAT_IDS}

QBT_URL=${QBT_URL}
QBT_SCHEME=${QBT_SCHEME}
QBT_HOST=${QBT_HOST}
QBT_PORT=${QBT_PORT}
QBT_USERNAME=${QBT_USERNAME}
QBT_PASSWORD=${QBT_PASSWORD}
QBT_SAVE_PATH=${QBT_SAVE_PATH}
QBT_CATEGORY=${QBT_CATEGORY}
QBT_TAGS=${QBT_TAGS}
ADD_STOPPED=${ADD_STOPPED}

USE_LOCAL_TELEGRAM_API=${USE_LOCAL_TELEGRAM_API}
LOCAL_TELEGRAM_FILE_ROOT=${LOCAL_TELEGRAM_FILE_ROOT}
EOF

chmod 600 "$ENV_FILE" 2>/dev/null || true

printf "\n"
printf "✅ 配置已生成：%s\n" "$ENV_FILE"
printf "\n"
printf "当前 qBittorrent 地址：%s\n" "$QBT_URL"
printf "Telegram API：%s\n" "$TELEGRAM_API_BASE"
printf "\n"
printf "下一步：\n"
printf "1. 如果是首次安装，运行：sh scripts/install.sh\n"
printf "2. 如果容器已经运行，执行：docker restart qbt-telegram-bot\n"
printf "3. 然后在 Telegram 发送：/test\n"
